from __future__ import annotations


ERR_POLICY_BLOCKED = "policy_blocked"
ERR_RESOLVE_NOT_FOUND = "resolve_not_found"
ERR_RESOLVE_AMBIGUOUS = "resolve_ambiguous"
ERR_QUOTA_EXCEEDED = "quota_exceeded"
ERR_UPSTREAM_TEMPORARY_FAILURE = "upstream_temporary_failure"

CODE_TOOL_NOT_ALLOWED = 4031
CODE_POLICY_BLOCKED = 4032
CODE_RESOLVE_NOT_FOUND = 4221
CODE_RESOLVE_AMBIGUOUS = 4222
CODE_QUOTA_EXCEEDED = 4291
CODE_UPSTREAM_TEMPORARY_FAILURE = 5031
